FROM python:3.12-slim

WORKDIR /app
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

COPY requirements-backend.txt requirements-dev.txt ./
RUN pip install --no-cache-dir -r requirements-backend.txt -r requirements-dev.txt

COPY . .

CMD ["python3", "-m", "pytest", "-v"]
